package study.proto;// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: person.proto

public final class PersonModel {
    private PersonModel() {
    }

    public static void registerAllExtensions(
            com.google.protobuf.ExtensionRegistryLite registry) {
    }

    public static void registerAllExtensions(
            com.google.protobuf.ExtensionRegistry registry) {
        registerAllExtensions(
                (com.google.protobuf.ExtensionRegistryLite) registry);
    }

    public interface PersonOrBuilder extends
            // @@protoc_insertion_point(interface_extends:Person)
            com.google.protobuf.MessageOrBuilder {

        /**
         * <code>optional string name = 1;</code>
         */
        java.lang.String getName();

        /**
         * <code>optional string name = 1;</code>
         */
        com.google.protobuf.ByteString
        getNameBytes();

        /**
         * <code>optional int32 age = 2;</code>
         */
        int getAge();

        /**
         * <code>optional .Person.Gender gender = 3;</code>
         */
        int getGenderValue();

        /**
         * <code>optional .Person.Gender gender = 3;</code>
         */
        PersonModel.Person.Gender getGender();

        /**
         * <code>optional float height = 4;</code>
         */
        float getHeight();

        /**
         * <code>optional double weight = 5;</code>
         */
        double getWeight();

        /**
         * <code>optional .Person.Location location = 6;</code>
         */
        boolean hasLocation();

        /**
         * <code>optional .Person.Location location = 6;</code>
         */
        PersonModel.Person.Location getLocation();

        /**
         * <code>optional .Person.Location location = 6;</code>
         */
        PersonModel.Person.LocationOrBuilder getLocationOrBuilder();
    }

    /**
     * Protobuf type {@code Person}
     */
    public static final class Person extends
            com.google.protobuf.GeneratedMessageV3 implements
            // @@protoc_insertion_point(message_implements:Person)
            PersonOrBuilder {
        // Use Person.newBuilder() to construct.
        private Person(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
            super(builder);
        }

        private Person() {
            name_ = "";
            age_ = 0;
            gender_ = 0;
            height_ = 0F;
            weight_ = 0D;
        }

        @java.lang.Override
        public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
            return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
        }

        private Person(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            this();
            int mutable_bitField0_ = 0;
            try {
                boolean done = false;
                while (!done) {
                    int tag = input.readTag();
                    switch (tag) {
                        case 0:
                            done = true;
                            break;
                        default: {
                            if (!input.skipField(tag)) {
                                done = true;
                            }
                            break;
                        }
                        case 10: {
                            java.lang.String s = input.readStringRequireUtf8();

                            name_ = s;
                            break;
                        }
                        case 16: {

                            age_ = input.readInt32();
                            break;
                        }
                        case 24: {
                            int rawValue = input.readEnum();

                            gender_ = rawValue;
                            break;
                        }
                        case 37: {

                            height_ = input.readFloat();
                            break;
                        }
                        case 41: {

                            weight_ = input.readDouble();
                            break;
                        }
                        case 50: {
                            PersonModel.Person.Location.Builder subBuilder = null;
                            if (location_ != null) {
                                subBuilder = location_.toBuilder();
                            }
                            location_ = input.readMessage(PersonModel.Person.Location.parser(), extensionRegistry);
                            if (subBuilder != null) {
                                subBuilder.mergeFrom(location_);
                                location_ = subBuilder.buildPartial();
                            }

                            break;
                        }
                    }
                }
            } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                throw e.setUnfinishedMessage(this);
            } catch (java.io.IOException e) {
                throw new com.google.protobuf.InvalidProtocolBufferException(
                        e).setUnfinishedMessage(this);
            } finally {
                makeExtensionsImmutable();
            }
        }

        public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
            return PersonModel.internal_static_Person_descriptor;
        }

        @Override
        protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
            return PersonModel.internal_static_Person_fieldAccessorTable
                    .ensureFieldAccessorsInitialized(
                            PersonModel.Person.class, PersonModel.Person.Builder.class);
        }

        /**
         * Protobuf enum {@code Person.Gender}
         */
        public enum Gender
                implements com.google.protobuf.ProtocolMessageEnum {
            /**
             * <code>man = 0;</code>
             */
            man(0),
            /**
             * <code>woman = 1;</code>
             */
            woman(1),
            UNRECOGNIZED(-1),
            ;

            /**
             * <code>man = 0;</code>
             */
            public static final int man_VALUE = 0;
            /**
             * <code>woman = 1;</code>
             */
            public static final int woman_VALUE = 1;


            @Override
            public final int getNumber() {
                if (this == UNRECOGNIZED) {
                    throw new java.lang.IllegalArgumentException(
                            "Can't get the number of an unknown enum value.");
                }
                return value;
            }

            /**
             * @deprecated Use {@link #forNumber(int)} instead.
             */
            @java.lang.Deprecated
            public static Gender valueOf(int value) {
                return forNumber(value);
            }

            public static Gender forNumber(int value) {
                switch (value) {
                    case 0:
                        return man;
                    case 1:
                        return woman;
                    default:
                        return null;
                }
            }

            public static com.google.protobuf.Internal.EnumLiteMap<Gender>
            internalGetValueMap() {
                return internalValueMap;
            }

            private static final com.google.protobuf.Internal.EnumLiteMap<
                    Gender> internalValueMap =
                    new com.google.protobuf.Internal.EnumLiteMap<Gender>() {
                        @Override
                        public Gender findValueByNumber(int number) {
                            return Gender.forNumber(number);
                        }
                    };

            @Override
            public final com.google.protobuf.Descriptors.EnumValueDescriptor
            getValueDescriptor() {
                return getDescriptor().getValues().get(ordinal());
            }

            @Override
            public final com.google.protobuf.Descriptors.EnumDescriptor
            getDescriptorForType() {
                return getDescriptor();
            }

            public static final com.google.protobuf.Descriptors.EnumDescriptor
            getDescriptor() {
                return PersonModel.Person.getDescriptor().getEnumTypes().get(0);
            }

            private static final Gender[] VALUES = values();

            public static Gender valueOf(
                    com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
                if (desc.getType() != getDescriptor()) {
                    throw new java.lang.IllegalArgumentException(
                            "EnumValueDescriptor is not for this type.");
                }
                if (desc.getIndex() == -1) {
                    return UNRECOGNIZED;
                }
                return VALUES[desc.getIndex()];
            }

            private final int value;

            private Gender(int value) {
                this.value = value;
            }

            // @@protoc_insertion_point(enum_scope:Person.Gender)
        }

        public interface LocationOrBuilder extends
                // @@protoc_insertion_point(interface_extends:Person.Location)
                com.google.protobuf.MessageOrBuilder {

            /**
             * <code>optional string placeName = 1;</code>
             */
            java.lang.String getPlaceName();

            /**
             * <code>optional string placeName = 1;</code>
             */
            com.google.protobuf.ByteString
            getPlaceNameBytes();

            /**
             * <code>optional uint64 placeId = 2;</code>
             */
            long getPlaceId();
        }

        /**
         * Protobuf type {@code Person.Location}
         */
        public static final class Location extends
                com.google.protobuf.GeneratedMessageV3 implements
                // @@protoc_insertion_point(message_implements:Person.Location)
                LocationOrBuilder {
            // Use Location.newBuilder() to construct.
            private Location(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
                super(builder);
            }

            private Location() {
                placeName_ = "";
                placeId_ = 0L;
            }

            @java.lang.Override
            public final com.google.protobuf.UnknownFieldSet
            getUnknownFields() {
                return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
            }

            private Location(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws com.google.protobuf.InvalidProtocolBufferException {
                this();
                int mutable_bitField0_ = 0;
                try {
                    boolean done = false;
                    while (!done) {
                        int tag = input.readTag();
                        switch (tag) {
                            case 0:
                                done = true;
                                break;
                            default: {
                                if (!input.skipField(tag)) {
                                    done = true;
                                }
                                break;
                            }
                            case 10: {
                                java.lang.String s = input.readStringRequireUtf8();

                                placeName_ = s;
                                break;
                            }
                            case 16: {

                                placeId_ = input.readUInt64();
                                break;
                            }
                        }
                    }
                } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                    throw e.setUnfinishedMessage(this);
                } catch (java.io.IOException e) {
                    throw new com.google.protobuf.InvalidProtocolBufferException(
                            e).setUnfinishedMessage(this);
                } finally {
                    makeExtensionsImmutable();
                }
            }

            public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
                return PersonModel.internal_static_Person_Location_descriptor;
            }

            @Override
            protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internalGetFieldAccessorTable() {
                return PersonModel.internal_static_Person_Location_fieldAccessorTable
                        .ensureFieldAccessorsInitialized(
                                PersonModel.Person.Location.class, PersonModel.Person.Location.Builder.class);
            }

            public static final int PLACENAME_FIELD_NUMBER = 1;
            private volatile java.lang.Object placeName_;

            /**
             * <code>optional string placeName = 1;</code>
             */
            @Override
            public java.lang.String getPlaceName() {
                java.lang.Object ref = placeName_;
                if (ref instanceof java.lang.String) {
                    return (java.lang.String) ref;
                } else {
                    com.google.protobuf.ByteString bs =
                            (com.google.protobuf.ByteString) ref;
                    java.lang.String s = bs.toStringUtf8();
                    placeName_ = s;
                    return s;
                }
            }

            /**
             * <code>optional string placeName = 1;</code>
             */
            @Override
            public com.google.protobuf.ByteString
            getPlaceNameBytes() {
                java.lang.Object ref = placeName_;
                if (ref instanceof java.lang.String) {
                    com.google.protobuf.ByteString b =
                            com.google.protobuf.ByteString.copyFromUtf8(
                                    (java.lang.String) ref);
                    placeName_ = b;
                    return b;
                } else {
                    return (com.google.protobuf.ByteString) ref;
                }
            }

            public static final int PLACEID_FIELD_NUMBER = 2;
            private long placeId_;

            /**
             * <code>optional uint64 placeId = 2;</code>
             */
            @Override
            public long getPlaceId() {
                return placeId_;
            }

            private byte memoizedIsInitialized = -1;

            @Override
            public final boolean isInitialized() {
                byte isInitialized = memoizedIsInitialized;
                if (isInitialized == 1) {
                    return true;
                }
                if (isInitialized == 0) {
                    return false;
                }

                memoizedIsInitialized = 1;
                return true;
            }

            @Override
            public void writeTo(com.google.protobuf.CodedOutputStream output)
                    throws java.io.IOException {
                if (!getPlaceNameBytes().isEmpty()) {
                    com.google.protobuf.GeneratedMessageV3.writeString(output, 1, placeName_);
                }
                if (placeId_ != 0L) {
                    output.writeUInt64(2, placeId_);
                }
            }

            @Override
            public int getSerializedSize() {
                int size = memoizedSize;
                if (size != -1) {
                    return size;
                }

                size = 0;
                if (!getPlaceNameBytes().isEmpty()) {
                    size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, placeName_);
                }
                if (placeId_ != 0L) {
                    size += com.google.protobuf.CodedOutputStream
                            .computeUInt64Size(2, placeId_);
                }
                memoizedSize = size;
                return size;
            }

            private static final long serialVersionUID = 0L;

            @java.lang.Override
            public boolean equals(final java.lang.Object obj) {
                if (obj == this) {
                    return true;
                }
                if (!(obj instanceof PersonModel.Person.Location)) {
                    return super.equals(obj);
                }
                PersonModel.Person.Location other = (PersonModel.Person.Location) obj;

                boolean result = true;
                result = result && getPlaceName()
                        .equals(other.getPlaceName());
                result = result && (getPlaceId()
                        == other.getPlaceId());
                return result;
            }

            @java.lang.Override
            public int hashCode() {
                if (memoizedHashCode != 0) {
                    return memoizedHashCode;
                }
                int hash = 41;
                hash = (19 * hash) + getDescriptorForType().hashCode();
                hash = (37 * hash) + PLACENAME_FIELD_NUMBER;
                hash = (53 * hash) + getPlaceName().hashCode();
                hash = (37 * hash) + PLACEID_FIELD_NUMBER;
                hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
                        getPlaceId());
                hash = (29 * hash) + unknownFields.hashCode();
                memoizedHashCode = hash;
                return hash;
            }

            public static PersonModel.Person.Location parseFrom(
                    com.google.protobuf.ByteString data)
                    throws com.google.protobuf.InvalidProtocolBufferException {
                return PARSER.parseFrom(data);
            }

            public static PersonModel.Person.Location parseFrom(
                    com.google.protobuf.ByteString data,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws com.google.protobuf.InvalidProtocolBufferException {
                return PARSER.parseFrom(data, extensionRegistry);
            }

            public static PersonModel.Person.Location parseFrom(byte[] data)
                    throws com.google.protobuf.InvalidProtocolBufferException {
                return PARSER.parseFrom(data);
            }

            public static PersonModel.Person.Location parseFrom(
                    byte[] data,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws com.google.protobuf.InvalidProtocolBufferException {
                return PARSER.parseFrom(data, extensionRegistry);
            }

            public static PersonModel.Person.Location parseFrom(java.io.InputStream input)
                    throws java.io.IOException {
                return com.google.protobuf.GeneratedMessageV3
                        .parseWithIOException(PARSER, input);
            }

            public static PersonModel.Person.Location parseFrom(
                    java.io.InputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws java.io.IOException {
                return com.google.protobuf.GeneratedMessageV3
                        .parseWithIOException(PARSER, input, extensionRegistry);
            }

            public static PersonModel.Person.Location parseDelimitedFrom(java.io.InputStream input)
                    throws java.io.IOException {
                return com.google.protobuf.GeneratedMessageV3
                        .parseDelimitedWithIOException(PARSER, input);
            }

            public static PersonModel.Person.Location parseDelimitedFrom(
                    java.io.InputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws java.io.IOException {
                return com.google.protobuf.GeneratedMessageV3
                        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
            }

            public static PersonModel.Person.Location parseFrom(
                    com.google.protobuf.CodedInputStream input)
                    throws java.io.IOException {
                return com.google.protobuf.GeneratedMessageV3
                        .parseWithIOException(PARSER, input);
            }

            public static PersonModel.Person.Location parseFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws java.io.IOException {
                return com.google.protobuf.GeneratedMessageV3
                        .parseWithIOException(PARSER, input, extensionRegistry);
            }

            @Override
            public Builder newBuilderForType() {
                return newBuilder();
            }

            public static Builder newBuilder() {
                return DEFAULT_INSTANCE.toBuilder();
            }

            public static Builder newBuilder(PersonModel.Person.Location prototype) {
                return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
            }

            @Override
            public Builder toBuilder() {
                return this == DEFAULT_INSTANCE
                        ? new Builder() : new Builder().mergeFrom(this);
            }

            @java.lang.Override
            protected Builder newBuilderForType(
                    com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
                Builder builder = new Builder(parent);
                return builder;
            }

            /**
             * Protobuf type {@code Person.Location}
             */
            public static final class Builder extends
                    com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
                    // @@protoc_insertion_point(builder_implements:Person.Location)
                    PersonModel.Person.LocationOrBuilder {
                public static final com.google.protobuf.Descriptors.Descriptor
                getDescriptor() {
                    return PersonModel.internal_static_Person_Location_descriptor;
                }

                @Override
                protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
                internalGetFieldAccessorTable() {
                    return PersonModel.internal_static_Person_Location_fieldAccessorTable
                            .ensureFieldAccessorsInitialized(
                                    PersonModel.Person.Location.class, PersonModel.Person.Location.Builder.class);
                }

                // Construct using PersonModel.Person.Location.newBuilder()
                private Builder() {
                    maybeForceBuilderInitialization();
                }

                private Builder(
                        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
                    super(parent);
                    maybeForceBuilderInitialization();
                }

                private void maybeForceBuilderInitialization() {
                    if (com.google.protobuf.GeneratedMessageV3
                            .alwaysUseFieldBuilders) {
                    }
                }

                @Override
                public Builder clear() {
                    super.clear();
                    placeName_ = "";

                    placeId_ = 0L;

                    return this;
                }

                @Override
                public com.google.protobuf.Descriptors.Descriptor
                getDescriptorForType() {
                    return PersonModel.internal_static_Person_Location_descriptor;
                }

                @Override
                public PersonModel.Person.Location getDefaultInstanceForType() {
                    return PersonModel.Person.Location.getDefaultInstance();
                }

                @Override
                public PersonModel.Person.Location build() {
                    PersonModel.Person.Location result = buildPartial();
                    if (!result.isInitialized()) {
                        throw newUninitializedMessageException(result);
                    }
                    return result;
                }

                @Override
                public PersonModel.Person.Location buildPartial() {
                    PersonModel.Person.Location result = new PersonModel.Person.Location(this);
                    result.placeName_ = placeName_;
                    result.placeId_ = placeId_;
                    onBuilt();
                    return result;
                }

                @Override
                public Builder clone() {
                    return (Builder) super.clone();
                }

                @Override
                public Builder setField(
                        com.google.protobuf.Descriptors.FieldDescriptor field,
                        Object value) {
                    return (Builder) super.setField(field, value);
                }

                @Override
                public Builder clearField(
                        com.google.protobuf.Descriptors.FieldDescriptor field) {
                    return (Builder) super.clearField(field);
                }

                @Override
                public Builder clearOneof(
                        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
                    return (Builder) super.clearOneof(oneof);
                }

                @Override
                public Builder setRepeatedField(
                        com.google.protobuf.Descriptors.FieldDescriptor field,
                        int index, Object value) {
                    return (Builder) super.setRepeatedField(field, index, value);
                }

                @Override
                public Builder addRepeatedField(
                        com.google.protobuf.Descriptors.FieldDescriptor field,
                        Object value) {
                    return (Builder) super.addRepeatedField(field, value);
                }

                @Override
                public Builder mergeFrom(com.google.protobuf.Message other) {
                    if (other instanceof PersonModel.Person.Location) {
                        return mergeFrom((PersonModel.Person.Location) other);
                    } else {
                        super.mergeFrom(other);
                        return this;
                    }
                }

                public Builder mergeFrom(PersonModel.Person.Location other) {
                    if (other == PersonModel.Person.Location.getDefaultInstance()) {
                        return this;
                    }
                    if (!other.getPlaceName().isEmpty()) {
                        placeName_ = other.placeName_;
                        onChanged();
                    }
                    if (other.getPlaceId() != 0L) {
                        setPlaceId(other.getPlaceId());
                    }
                    onChanged();
                    return this;
                }

                @Override
                public final boolean isInitialized() {
                    return true;
                }

                @Override
                public Builder mergeFrom(
                        com.google.protobuf.CodedInputStream input,
                        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                        throws java.io.IOException {
                    PersonModel.Person.Location parsedMessage = null;
                    try {
                        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
                    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                        parsedMessage = (PersonModel.Person.Location) e.getUnfinishedMessage();
                        throw e.unwrapIOException();
                    } finally {
                        if (parsedMessage != null) {
                            mergeFrom(parsedMessage);
                        }
                    }
                    return this;
                }

                private java.lang.Object placeName_ = "";

                /**
                 * <code>optional string placeName = 1;</code>
                 */
                @Override
                public java.lang.String getPlaceName() {
                    java.lang.Object ref = placeName_;
                    if (!(ref instanceof java.lang.String)) {
                        com.google.protobuf.ByteString bs =
                                (com.google.protobuf.ByteString) ref;
                        java.lang.String s = bs.toStringUtf8();
                        placeName_ = s;
                        return s;
                    } else {
                        return (java.lang.String) ref;
                    }
                }

                /**
                 * <code>optional string placeName = 1;</code>
                 */
                @Override
                public com.google.protobuf.ByteString
                getPlaceNameBytes() {
                    java.lang.Object ref = placeName_;
                    if (ref instanceof String) {
                        com.google.protobuf.ByteString b =
                                com.google.protobuf.ByteString.copyFromUtf8(
                                        (java.lang.String) ref);
                        placeName_ = b;
                        return b;
                    } else {
                        return (com.google.protobuf.ByteString) ref;
                    }
                }

                /**
                 * <code>optional string placeName = 1;</code>
                 */
                public Builder setPlaceName(
                        java.lang.String value) {
                    if (value == null) {
                        throw new NullPointerException();
                    }

                    placeName_ = value;
                    onChanged();
                    return this;
                }

                /**
                 * <code>optional string placeName = 1;</code>
                 */
                public Builder clearPlaceName() {

                    placeName_ = getDefaultInstance().getPlaceName();
                    onChanged();
                    return this;
                }

                /**
                 * <code>optional string placeName = 1;</code>
                 */
                public Builder setPlaceNameBytes(
                        com.google.protobuf.ByteString value) {
                    if (value == null) {
                        throw new NullPointerException();
                    }
                    checkByteStringIsUtf8(value);

                    placeName_ = value;
                    onChanged();
                    return this;
                }

                private long placeId_;

                /**
                 * <code>optional uint64 placeId = 2;</code>
                 */
                @Override
                public long getPlaceId() {
                    return placeId_;
                }

                /**
                 * <code>optional uint64 placeId = 2;</code>
                 */
                public Builder setPlaceId(long value) {

                    placeId_ = value;
                    onChanged();
                    return this;
                }

                /**
                 * <code>optional uint64 placeId = 2;</code>
                 */
                public Builder clearPlaceId() {

                    placeId_ = 0L;
                    onChanged();
                    return this;
                }

                @Override
                public final Builder setUnknownFields(
                        final com.google.protobuf.UnknownFieldSet unknownFields) {
                    return this;
                }

                @Override
                public final Builder mergeUnknownFields(
                        final com.google.protobuf.UnknownFieldSet unknownFields) {
                    return this;
                }


                // @@protoc_insertion_point(builder_scope:Person.Location)
            }

            // @@protoc_insertion_point(class_scope:Person.Location)
            private static final PersonModel.Person.Location DEFAULT_INSTANCE;

            static {
                DEFAULT_INSTANCE = new PersonModel.Person.Location();
            }

            public static PersonModel.Person.Location getDefaultInstance() {
                return DEFAULT_INSTANCE;
            }

            private static final com.google.protobuf.Parser<Location>
                    PARSER = new com.google.protobuf.AbstractParser<Location>() {
                @Override
                public Location parsePartialFrom(
                        com.google.protobuf.CodedInputStream input,
                        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                        throws com.google.protobuf.InvalidProtocolBufferException {
                    return new Location(input, extensionRegistry);
                }
            };

            public static com.google.protobuf.Parser<Location> parser() {
                return PARSER;
            }

            @java.lang.Override
            public com.google.protobuf.Parser<Location> getParserForType() {
                return PARSER;
            }

            @Override
            public PersonModel.Person.Location getDefaultInstanceForType() {
                return DEFAULT_INSTANCE;
            }

        }

        public static final int NAME_FIELD_NUMBER = 1;
        private volatile java.lang.Object name_;

        /**
         * <code>optional string name = 1;</code>
         */
        @Override
        public java.lang.String getName() {
            java.lang.Object ref = name_;
            if (ref instanceof java.lang.String) {
                return (java.lang.String) ref;
            } else {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                java.lang.String s = bs.toStringUtf8();
                name_ = s;
                return s;
            }
        }

        /**
         * <code>optional string name = 1;</code>
         */
        @Override
        public com.google.protobuf.ByteString
        getNameBytes() {
            java.lang.Object ref = name_;
            if (ref instanceof java.lang.String) {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8(
                                (java.lang.String) ref);
                name_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        public static final int AGE_FIELD_NUMBER = 2;
        private int age_;

        /**
         * <code>optional int32 age = 2;</code>
         */
        @Override
        public int getAge() {
            return age_;
        }

        public static final int GENDER_FIELD_NUMBER = 3;
        private int gender_;

        /**
         * <code>optional .Person.Gender gender = 3;</code>
         */
        @Override
        public int getGenderValue() {
            return gender_;
        }

        /**
         * <code>optional .Person.Gender gender = 3;</code>
         */
        @Override
        public PersonModel.Person.Gender getGender() {
            PersonModel.Person.Gender result = PersonModel.Person.Gender.valueOf(gender_);
            return result == null ? PersonModel.Person.Gender.UNRECOGNIZED : result;
        }

        public static final int HEIGHT_FIELD_NUMBER = 4;
        private float height_;

        /**
         * <code>optional float height = 4;</code>
         */
        @Override
        public float getHeight() {
            return height_;
        }

        public static final int WEIGHT_FIELD_NUMBER = 5;
        private double weight_;

        /**
         * <code>optional double weight = 5;</code>
         */
        @Override
        public double getWeight() {
            return weight_;
        }

        public static final int LOCATION_FIELD_NUMBER = 6;
        private PersonModel.Person.Location location_;

        /**
         * <code>optional .Person.Location location = 6;</code>
         */
        @Override
        public boolean hasLocation() {
            return location_ != null;
        }

        /**
         * <code>optional .Person.Location location = 6;</code>
         */
        @Override
        public PersonModel.Person.Location getLocation() {
            return location_ == null ? PersonModel.Person.Location.getDefaultInstance() : location_;
        }

        /**
         * <code>optional .Person.Location location = 6;</code>
         */
        @Override
        public PersonModel.Person.LocationOrBuilder getLocationOrBuilder() {
            return getLocation();
        }

        private byte memoizedIsInitialized = -1;

        @Override
        public final boolean isInitialized() {
            byte isInitialized = memoizedIsInitialized;
            if (isInitialized == 1) {
                return true;
            }
            if (isInitialized == 0) {
                return false;
            }

            memoizedIsInitialized = 1;
            return true;
        }

        @Override
        public void writeTo(com.google.protobuf.CodedOutputStream output)
                throws java.io.IOException {
            if (!getNameBytes().isEmpty()) {
                com.google.protobuf.GeneratedMessageV3.writeString(output, 1, name_);
            }
            if (age_ != 0) {
                output.writeInt32(2, age_);
            }
            if (gender_ != PersonModel.Person.Gender.man.getNumber()) {
                output.writeEnum(3, gender_);
            }
            if (height_ != 0F) {
                output.writeFloat(4, height_);
            }
            if (weight_ != 0D) {
                output.writeDouble(5, weight_);
            }
            if (location_ != null) {
                output.writeMessage(6, getLocation());
            }
        }

        @Override
        public int getSerializedSize() {
            int size = memoizedSize;
            if (size != -1) {
                return size;
            }

            size = 0;
            if (!getNameBytes().isEmpty()) {
                size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, name_);
            }
            if (age_ != 0) {
                size += com.google.protobuf.CodedOutputStream
                        .computeInt32Size(2, age_);
            }
            if (gender_ != PersonModel.Person.Gender.man.getNumber()) {
                size += com.google.protobuf.CodedOutputStream
                        .computeEnumSize(3, gender_);
            }
            if (height_ != 0F) {
                size += com.google.protobuf.CodedOutputStream
                        .computeFloatSize(4, height_);
            }
            if (weight_ != 0D) {
                size += com.google.protobuf.CodedOutputStream
                        .computeDoubleSize(5, weight_);
            }
            if (location_ != null) {
                size += com.google.protobuf.CodedOutputStream
                        .computeMessageSize(6, getLocation());
            }
            memoizedSize = size;
            return size;
        }

        private static final long serialVersionUID = 0L;

        @java.lang.Override
        public boolean equals(final java.lang.Object obj) {
            if (obj == this) {
                return true;
            }
            if (!(obj instanceof PersonModel.Person)) {
                return super.equals(obj);
            }
            PersonModel.Person other = (PersonModel.Person) obj;

            boolean result = true;
            result = result && getName()
                    .equals(other.getName());
            result = result && (getAge()
                    == other.getAge());
            result = result && gender_ == other.gender_;
            result = result && (
                    java.lang.Float.floatToIntBits(getHeight())
                            == java.lang.Float.floatToIntBits(
                            other.getHeight()));
            result = result && (
                    java.lang.Double.doubleToLongBits(getWeight())
                            == java.lang.Double.doubleToLongBits(
                            other.getWeight()));
            result = result && (hasLocation() == other.hasLocation());
            if (hasLocation()) {
                result = result && getLocation()
                        .equals(other.getLocation());
            }
            return result;
        }

        @java.lang.Override
        public int hashCode() {
            if (memoizedHashCode != 0) {
                return memoizedHashCode;
            }
            int hash = 41;
            hash = (19 * hash) + getDescriptorForType().hashCode();
            hash = (37 * hash) + NAME_FIELD_NUMBER;
            hash = (53 * hash) + getName().hashCode();
            hash = (37 * hash) + AGE_FIELD_NUMBER;
            hash = (53 * hash) + getAge();
            hash = (37 * hash) + GENDER_FIELD_NUMBER;
            hash = (53 * hash) + gender_;
            hash = (37 * hash) + HEIGHT_FIELD_NUMBER;
            hash = (53 * hash) + java.lang.Float.floatToIntBits(
                    getHeight());
            hash = (37 * hash) + WEIGHT_FIELD_NUMBER;
            hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
                    java.lang.Double.doubleToLongBits(getWeight()));
            if (hasLocation()) {
                hash = (37 * hash) + LOCATION_FIELD_NUMBER;
                hash = (53 * hash) + getLocation().hashCode();
            }
            hash = (29 * hash) + unknownFields.hashCode();
            memoizedHashCode = hash;
            return hash;
        }

        public static PersonModel.Person parseFrom(
                com.google.protobuf.ByteString data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static PersonModel.Person parseFrom(
                com.google.protobuf.ByteString data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static PersonModel.Person parseFrom(byte[] data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static PersonModel.Person parseFrom(
                byte[] data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static PersonModel.Person parseFrom(java.io.InputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input);
        }

        public static PersonModel.Person parseFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input, extensionRegistry);
        }

        public static PersonModel.Person parseDelimitedFrom(java.io.InputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseDelimitedWithIOException(PARSER, input);
        }

        public static PersonModel.Person parseDelimitedFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
        }

        public static PersonModel.Person parseFrom(
                com.google.protobuf.CodedInputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input);
        }

        public static PersonModel.Person parseFrom(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input, extensionRegistry);
        }

        @Override
        public Builder newBuilderForType() {
            return newBuilder();
        }

        public static Builder newBuilder() {
            return DEFAULT_INSTANCE.toBuilder();
        }

        public static Builder newBuilder(PersonModel.Person prototype) {
            return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
        }

        @Override
        public Builder toBuilder() {
            return this == DEFAULT_INSTANCE
                    ? new Builder() : new Builder().mergeFrom(this);
        }

        @java.lang.Override
        protected Builder newBuilderForType(
                com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
            Builder builder = new Builder(parent);
            return builder;
        }

        /**
         * Protobuf type {@code Person}
         */
        public static final class Builder extends
                com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
                // @@protoc_insertion_point(builder_implements:Person)
                PersonModel.PersonOrBuilder {
            public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
                return PersonModel.internal_static_Person_descriptor;
            }

            @Override
            protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internalGetFieldAccessorTable() {
                return PersonModel.internal_static_Person_fieldAccessorTable
                        .ensureFieldAccessorsInitialized(
                                PersonModel.Person.class, PersonModel.Person.Builder.class);
            }

            // Construct using PersonModel.Person.newBuilder()
            private Builder() {
                maybeForceBuilderInitialization();
            }

            private Builder(
                    com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
                super(parent);
                maybeForceBuilderInitialization();
            }

            private void maybeForceBuilderInitialization() {
                if (com.google.protobuf.GeneratedMessageV3
                        .alwaysUseFieldBuilders) {
                }
            }

            @Override
            public Builder clear() {
                super.clear();
                name_ = "";

                age_ = 0;

                gender_ = 0;

                height_ = 0F;

                weight_ = 0D;

                if (locationBuilder_ == null) {
                    location_ = null;
                } else {
                    location_ = null;
                    locationBuilder_ = null;
                }
                return this;
            }

            @Override
            public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
                return PersonModel.internal_static_Person_descriptor;
            }

            @Override
            public PersonModel.Person getDefaultInstanceForType() {
                return PersonModel.Person.getDefaultInstance();
            }

            @Override
            public PersonModel.Person build() {
                PersonModel.Person result = buildPartial();
                if (!result.isInitialized()) {
                    throw newUninitializedMessageException(result);
                }
                return result;
            }

            @Override
            public PersonModel.Person buildPartial() {
                PersonModel.Person result = new PersonModel.Person(this);
                result.name_ = name_;
                result.age_ = age_;
                result.gender_ = gender_;
                result.height_ = height_;
                result.weight_ = weight_;
                if (locationBuilder_ == null) {
                    result.location_ = location_;
                } else {
                    result.location_ = locationBuilder_.build();
                }
                onBuilt();
                return result;
            }

            @Override
            public Builder clone() {
                return (Builder) super.clone();
            }

            @Override
            public Builder setField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    Object value) {
                return (Builder) super.setField(field, value);
            }

            @Override
            public Builder clearField(
                    com.google.protobuf.Descriptors.FieldDescriptor field) {
                return (Builder) super.clearField(field);
            }

            @Override
            public Builder clearOneof(
                    com.google.protobuf.Descriptors.OneofDescriptor oneof) {
                return (Builder) super.clearOneof(oneof);
            }

            @Override
            public Builder setRepeatedField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    int index, Object value) {
                return (Builder) super.setRepeatedField(field, index, value);
            }

            @Override
            public Builder addRepeatedField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    Object value) {
                return (Builder) super.addRepeatedField(field, value);
            }

            @Override
            public Builder mergeFrom(com.google.protobuf.Message other) {
                if (other instanceof PersonModel.Person) {
                    return mergeFrom((PersonModel.Person) other);
                } else {
                    super.mergeFrom(other);
                    return this;
                }
            }

            public Builder mergeFrom(PersonModel.Person other) {
                if (other == PersonModel.Person.getDefaultInstance()) {
                    return this;
                }
                if (!other.getName().isEmpty()) {
                    name_ = other.name_;
                    onChanged();
                }
                if (other.getAge() != 0) {
                    setAge(other.getAge());
                }
                if (other.gender_ != 0) {
                    setGenderValue(other.getGenderValue());
                }
                if (other.getHeight() != 0F) {
                    setHeight(other.getHeight());
                }
                if (other.getWeight() != 0D) {
                    setWeight(other.getWeight());
                }
                if (other.hasLocation()) {
                    mergeLocation(other.getLocation());
                }
                onChanged();
                return this;
            }

            @Override
            public final boolean isInitialized() {
                return true;
            }

            @Override
            public Builder mergeFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws java.io.IOException {
                PersonModel.Person parsedMessage = null;
                try {
                    parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
                } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                    parsedMessage = (PersonModel.Person) e.getUnfinishedMessage();
                    throw e.unwrapIOException();
                } finally {
                    if (parsedMessage != null) {
                        mergeFrom(parsedMessage);
                    }
                }
                return this;
            }

            private java.lang.Object name_ = "";

            /**
             * <code>optional string name = 1;</code>
             */
            @Override
            public java.lang.String getName() {
                java.lang.Object ref = name_;
                if (!(ref instanceof java.lang.String)) {
                    com.google.protobuf.ByteString bs =
                            (com.google.protobuf.ByteString) ref;
                    java.lang.String s = bs.toStringUtf8();
                    name_ = s;
                    return s;
                } else {
                    return (java.lang.String) ref;
                }
            }

            /**
             * <code>optional string name = 1;</code>
             */
            @Override
            public com.google.protobuf.ByteString
            getNameBytes() {
                java.lang.Object ref = name_;
                if (ref instanceof String) {
                    com.google.protobuf.ByteString b =
                            com.google.protobuf.ByteString.copyFromUtf8(
                                    (java.lang.String) ref);
                    name_ = b;
                    return b;
                } else {
                    return (com.google.protobuf.ByteString) ref;
                }
            }

            /**
             * <code>optional string name = 1;</code>
             */
            public Builder setName(
                    java.lang.String value) {
                if (value == null) {
                    throw new NullPointerException();
                }

                name_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>optional string name = 1;</code>
             */
            public Builder clearName() {

                name_ = getDefaultInstance().getName();
                onChanged();
                return this;
            }

            /**
             * <code>optional string name = 1;</code>
             */
            public Builder setNameBytes(
                    com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                checkByteStringIsUtf8(value);

                name_ = value;
                onChanged();
                return this;
            }

            private int age_;

            /**
             * <code>optional int32 age = 2;</code>
             */
            @Override
            public int getAge() {
                return age_;
            }

            /**
             * <code>optional int32 age = 2;</code>
             */
            public Builder setAge(int value) {

                age_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>optional int32 age = 2;</code>
             */
            public Builder clearAge() {

                age_ = 0;
                onChanged();
                return this;
            }

            private int gender_ = 0;

            /**
             * <code>optional .Person.Gender gender = 3;</code>
             */
            @Override
            public int getGenderValue() {
                return gender_;
            }

            /**
             * <code>optional .Person.Gender gender = 3;</code>
             */
            public Builder setGenderValue(int value) {
                gender_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>optional .Person.Gender gender = 3;</code>
             */
            @Override
            public PersonModel.Person.Gender getGender() {
                PersonModel.Person.Gender result = PersonModel.Person.Gender.valueOf(gender_);
                return result == null ? PersonModel.Person.Gender.UNRECOGNIZED : result;
            }

            /**
             * <code>optional .Person.Gender gender = 3;</code>
             */
            public Builder setGender(PersonModel.Person.Gender value) {
                if (value == null) {
                    throw new NullPointerException();
                }

                gender_ = value.getNumber();
                onChanged();
                return this;
            }

            /**
             * <code>optional .Person.Gender gender = 3;</code>
             */
            public Builder clearGender() {

                gender_ = 0;
                onChanged();
                return this;
            }

            private float height_;

            /**
             * <code>optional float height = 4;</code>
             */
            @Override
            public float getHeight() {
                return height_;
            }

            /**
             * <code>optional float height = 4;</code>
             */
            public Builder setHeight(float value) {

                height_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>optional float height = 4;</code>
             */
            public Builder clearHeight() {

                height_ = 0F;
                onChanged();
                return this;
            }

            private double weight_;

            /**
             * <code>optional double weight = 5;</code>
             */
            @Override
            public double getWeight() {
                return weight_;
            }

            /**
             * <code>optional double weight = 5;</code>
             */
            public Builder setWeight(double value) {

                weight_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>optional double weight = 5;</code>
             */
            public Builder clearWeight() {

                weight_ = 0D;
                onChanged();
                return this;
            }

            private PersonModel.Person.Location location_ = null;
            private com.google.protobuf.SingleFieldBuilderV3<
                    PersonModel.Person.Location, PersonModel.Person.Location.Builder, PersonModel.Person.LocationOrBuilder> locationBuilder_;

            /**
             * <code>optional .Person.Location location = 6;</code>
             */
            @Override
            public boolean hasLocation() {
                return locationBuilder_ != null || location_ != null;
            }

            /**
             * <code>optional .Person.Location location = 6;</code>
             */
            @Override
            public PersonModel.Person.Location getLocation() {
                if (locationBuilder_ == null) {
                    return location_ == null ? PersonModel.Person.Location.getDefaultInstance() : location_;
                } else {
                    return locationBuilder_.getMessage();
                }
            }

            /**
             * <code>optional .Person.Location location = 6;</code>
             */
            public Builder setLocation(PersonModel.Person.Location value) {
                if (locationBuilder_ == null) {
                    if (value == null) {
                        throw new NullPointerException();
                    }
                    location_ = value;
                    onChanged();
                } else {
                    locationBuilder_.setMessage(value);
                }

                return this;
            }

            /**
             * <code>optional .Person.Location location = 6;</code>
             */
            public Builder setLocation(
                    PersonModel.Person.Location.Builder builderForValue) {
                if (locationBuilder_ == null) {
                    location_ = builderForValue.build();
                    onChanged();
                } else {
                    locationBuilder_.setMessage(builderForValue.build());
                }

                return this;
            }

            /**
             * <code>optional .Person.Location location = 6;</code>
             */
            public Builder mergeLocation(PersonModel.Person.Location value) {
                if (locationBuilder_ == null) {
                    if (location_ != null) {
                        location_ =
                                PersonModel.Person.Location.newBuilder(location_).mergeFrom(value).buildPartial();
                    } else {
                        location_ = value;
                    }
                    onChanged();
                } else {
                    locationBuilder_.mergeFrom(value);
                }

                return this;
            }

            /**
             * <code>optional .Person.Location location = 6;</code>
             */
            public Builder clearLocation() {
                if (locationBuilder_ == null) {
                    location_ = null;
                    onChanged();
                } else {
                    location_ = null;
                    locationBuilder_ = null;
                }

                return this;
            }

            /**
             * <code>optional .Person.Location location = 6;</code>
             */
            public PersonModel.Person.Location.Builder getLocationBuilder() {

                onChanged();
                return getLocationFieldBuilder().getBuilder();
            }

            /**
             * <code>optional .Person.Location location = 6;</code>
             */
            @Override
            public PersonModel.Person.LocationOrBuilder getLocationOrBuilder() {
                if (locationBuilder_ != null) {
                    return locationBuilder_.getMessageOrBuilder();
                } else {
                    return location_ == null ?
                            PersonModel.Person.Location.getDefaultInstance() : location_;
                }
            }

            /**
             * <code>optional .Person.Location location = 6;</code>
             */
            private com.google.protobuf.SingleFieldBuilderV3<
                    PersonModel.Person.Location, PersonModel.Person.Location.Builder, PersonModel.Person.LocationOrBuilder>
            getLocationFieldBuilder() {
                if (locationBuilder_ == null) {
                    locationBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
                            PersonModel.Person.Location, PersonModel.Person.Location.Builder, PersonModel.Person.LocationOrBuilder>(
                            getLocation(),
                            getParentForChildren(),
                            isClean());
                    location_ = null;
                }
                return locationBuilder_;
            }

            @Override
            public final Builder setUnknownFields(
                    final com.google.protobuf.UnknownFieldSet unknownFields) {
                return this;
            }

            @Override
            public final Builder mergeUnknownFields(
                    final com.google.protobuf.UnknownFieldSet unknownFields) {
                return this;
            }


            // @@protoc_insertion_point(builder_scope:Person)
        }

        // @@protoc_insertion_point(class_scope:Person)
        private static final PersonModel.Person DEFAULT_INSTANCE;

        static {
            DEFAULT_INSTANCE = new PersonModel.Person();
        }

        public static PersonModel.Person getDefaultInstance() {
            return DEFAULT_INSTANCE;
        }

        private static final com.google.protobuf.Parser<Person>
                PARSER = new com.google.protobuf.AbstractParser<Person>() {
            @Override
            public Person parsePartialFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws com.google.protobuf.InvalidProtocolBufferException {
                return new Person(input, extensionRegistry);
            }
        };

        public static com.google.protobuf.Parser<Person> parser() {
            return PARSER;
        }

        @java.lang.Override
        public com.google.protobuf.Parser<Person> getParserForType() {
            return PARSER;
        }

        @Override
        public PersonModel.Person getDefaultInstanceForType() {
            return DEFAULT_INSTANCE;
        }

    }

    private static final com.google.protobuf.Descriptors.Descriptor
            internal_static_Person_descriptor;
    private static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internal_static_Person_fieldAccessorTable;
    private static final com.google.protobuf.Descriptors.Descriptor
            internal_static_Person_Location_descriptor;
    private static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internal_static_Person_Location_fieldAccessorTable;

    public static com.google.protobuf.Descriptors.FileDescriptor
    getDescriptor() {
        return descriptor;
    }

    private static com.google.protobuf.Descriptors.FileDescriptor
            descriptor;

    static {
        java.lang.String[] descriptorData = {
                "\n\014person.proto\"\325\001\n\006Person\022\014\n\004name\030\001 \001(\t\022" +
                        "\013\n\003age\030\002 \001(\005\022\036\n\006gender\030\003 \001(\0162\016.Person.Ge" +
                        "nder\022\016\n\006height\030\004 \001(\002\022\016\n\006weight\030\005 \001(\001\022\"\n\010" +
                        "location\030\006 \001(\0132\020.Person.Location\032.\n\010Loca" +
                        "tion\022\021\n\tplaceName\030\001 \001(\t\022\017\n\007placeId\030\002 \001(\004" +
                        "\"\034\n\006Gender\022\007\n\003man\020\000\022\t\n\005woman\020\001B\rB\013Person" +
                        "Modelb\006proto3"
        };
        com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
                new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
                    @Override
                    public com.google.protobuf.ExtensionRegistry assignDescriptors(
                            com.google.protobuf.Descriptors.FileDescriptor root) {
                        descriptor = root;
                        return null;
                    }
                };
        com.google.protobuf.Descriptors.FileDescriptor
                .internalBuildGeneratedFileFrom(descriptorData,
                        new com.google.protobuf.Descriptors.FileDescriptor[]{
                        }, assigner);
        internal_static_Person_descriptor =
                getDescriptor().getMessageTypes().get(0);
        internal_static_Person_fieldAccessorTable = new
                com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
                internal_static_Person_descriptor,
                new java.lang.String[]{"Name", "Age", "Gender", "Height", "Weight", "Location",});
        internal_static_Person_Location_descriptor =
                internal_static_Person_descriptor.getNestedTypes().get(0);
        internal_static_Person_Location_fieldAccessorTable = new
                com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
                internal_static_Person_Location_descriptor,
                new java.lang.String[]{"PlaceName", "PlaceId",});
    }

    // @@protoc_insertion_point(outer_class_scope)
}
